---
title: "LJ003_limma"
author: "Libby Jennings"
date: "30/04/2020"
output: html_document
---
Overview of analysis
1. Read in counts data, metadata, matrisome gene masterlist 
2. Tidy counts data and prepare matrix
3. Normalisation with voom
4. Linear modelling and DE analysis with limma
5. Define DEGs
6. Filter for matrisome DEGs
7. Generate rank score using logFC*-log10(adj.p) and order matrisome DEGs



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(dplyr)
library(ggplot2)
library(edgeR)
library(ggVennDiagram)
library(ggrepel)
library(gplots)
library(RColorBrewer)


```

``` {r read in data}

counts_data <- read.csv("./data/GSE131032_kallisto_counts.csv")
log2pm <- read.csv("./data/log2pm_kallisto.csv")
metadata <- read.csv("./data/metadata.csv")

matrisome_masterlist <- read.csv("~/Documents/Bioinformatics/Matrisome/matrisome_mm_masterlist_plus.csv")
colnames(matrisome_masterlist) <- gsub(" ", ".", colnames(matrisome_masterlist))
names(matrisome_masterlist)[names(matrisome_masterlist) == "Gene.Symbol"] <- "gene"
matrisome <- matrisome_masterlist$gene

```

```{r tidy and prepare matrix}

# renames columns with sample names and rename rows with gene names
rownames(counts_data) <- counts_data$X
counts_data <- counts_data[,-1]
colnames(counts_data) <- metadata$SampleName

# convert to matrix
counts_data <- as.matrix(counts_data)

# convert metadata days to numeric
metadata$Day <- as.numeric(gsub("d", "", metadata$Day))

```

```{r voom preprocessing}

#create DGEList object
d0 <- DGEList(counts_data)

# calculate normalisation factors
d0.norm <- calcNormFactors(d0)

# filter out genes with a max count of less than 5 across all samples
cutoff <- 5
drop <- which(apply(cpm(d0.norm), 1, max) < cutoff)
d <- d0.norm[(-drop),]

dim(d)
# 12464         26

# pull out day predictor from metadata
day <- metadata$Day

plotMDS(d, col = as.numeric(day))

```

``` {r voom normalisation}
#create model matrix 
mm <- model.matrix(~day)
head(mm)
# carry out voom normalisation generate plot
y <- voom(d, mm, plot = T)

```

``` {r limma}

# fit linear model
fit <- lmFit(y, mm)
head(coef(fit))

### problem here?

### with contrasts
#contr <- contrasts.fit(fit, coefficients = 2)
#tmp <- contrasts.fit(fit, coef = "day")
#tmp <- eBayes(tmp)
#summary(decideTests(tmp))

### without contrasts
tmp <- eBayes(fit)
summary(decideTests(tmp))

#coefs <- as.data.frame(tmp$coefficients)
#coefs$gene <- rownames(coefs)
#qplot(data = coefs, x = day, xlab = "coefficient")

toptable <- topTable(tmp, sort.by = "none", n= Inf)
toptable$gene <- rownames(toptable)

# plot histogram of p values and logFCs
qplot(data = toptable, x = P.Value)
qplot(data = toptable, x = logFC)


```


```{r define DEGS}
# filter with logFC greater than 0.5 and FDR less than 0.05
# logFC threshold is arbitary
DEgenes <- filter(toptable, toptable$P.Value < 0.05 & abs(logFC) > 0.05)
dim(DEgenes)

topDEGs <- arrange(toptable, desc(abs(logFC)))[1:20,]

```

```{r volcano plot}

ggplot(data = toptable, aes(x = logFC, y = (-log10(P.Value)))) +
        geom_point(col = "#ffaa44", alpha = 0.5) +
        geom_point(data = DEgenes, aes(x = DEgenes$logFC, y= -log10(P.Value)), col = "black")

ggplot(data = toptable, aes(x = logFC, y = -log10(P.Value))) +
        geom_point(col = "grey") +
        geom_point(data = DEgenes, col = "red")
        geom_text_repel(data = topDEGs, aes(x = logFC, y = (-log10(P.Value)), label = topDEGs$gene))
        

```
``` {r check some top DEGs}

#generate df of normalised counts (cpm)

norm_counts <- as.data.frame(cpm(d))
norm_counts$gene <- rownames(norm_counts)

#plot cpm for example genes
# Lep
lep_counts <- filter(norm_counts, gene == "Lep")
lep_counts <- lep_counts[, 1:26]
lep_counts <- as.numeric(lep_counts[1,])

lep_df <- data.frame(Gene = "Lep", Day = day, norm_counts = lep_counts)

ggplot(lep_df, aes(x =as.factor(Day), y = norm_counts)) +
        geom_boxplot() +
        ggtitle("Normalised counts for Lep - DSS")

# RPS12l1
r_counts <- filter(norm_counts, gene == "Rps12l1")
r_counts <- r_counts[, 1:26]
r_counts <- as.numeric(r_counts[1,])

r_df <- data.frame(Gene = "Rps12l1", Day = day, counts = r_counts)

ggplot(r_df, aes(x =as.factor(Day), y = counts)) +
        geom_boxplot() +
        ggtitle("Normalised counts for Rps12l1 - DSS")


# Bre

bre_counts <- filter(norm_counts, gene == "Bre")
bre_counts <- bre_counts[, 1:26]
bre_counts <- as.numeric(bre_counts[1,])

bre_df <- data.frame(Gene = "bre", Day = day, counts = bre_counts)

ggplot(bre_df, aes(x =as.factor(Day), y = counts)) +
        geom_boxplot() +
        ggtitle("Normalised counts for Bre - DSS")


```

``` {r matrisome subsetting}

mx_DEGs <- filter(toptable, gene %in% matrisome)
dim(mx_DEGs) # 494 genes

# rank by logFC*adj.p.value
mx_degs <- mutate(mx_DEGs, rank.score = abs(logFC)*-log10(adj.P.Val))
mx_degs <- arrange(mx_degs, desc(rank.score))

# filter genes with P value < 0.05
mx_degs_sig <- filter(mx_degs, P.Value < 0.05)
dim(mx_degs_sig)

ggplot(data = toptable, aes(x = logFC, y = -log10(P.Value))) +
        geom_point(col = "grey", alpha = 0.5) +
        geom_point(data = mx_degs, aes(x = mx_degs$logFC, y= -log10(mx_degs$P.Value)), col = "#ffaa33", alpha = 0.2)+
        geom_point(data = mx_degs_sig, aes(x = mx_degs_sig$logFC, y= -log10(mx_degs_sig$P.Value), col = mx_degs_sig$rank.score)) +
        geom_text_repel(data = mx_degs_sig[1:10,], aes(x = logFC, y = (-log10(P.Value)), label = gene)) +
        geom_hline(yintercept = -log10(0.05)) +
        ggtitle("Volcano plot of log2FC per day vs P value")

        
```

```{r generate matrisome DEG output file}
# create a dataframe with matrisome genes (not filtered by significant p value)
# annotated with up/downregulation
mx_degs_output <- mutate(mx_degs, "up/down" = ifelse(mx_degs$logFC > 0, "up", "down"))
mx_degs_output <- join(mx_degs_output, matrisome_masterlist, by = "gene")

write.csv(mx_degs_output, file = "LJ003_DSS_mxdegs_unf.csv")

```


``` {r pie for lols}
# proprotion of matrisome DEGs identified in the study belonging to each category
ggplot(filter(matrisome_masterlist, gene %in% mx_degs$gene), aes(x=factor(1), fill=Category))+
  geom_bar(width = 1)+
  coord_polar("y") +
        xlab(label = "")

```

``` {r heatmap}
# plot heatmap of cpm across time for significant matrix genes

mx_counts <- filter(norm_counts, gene %in% mx_degs_sig$gene)
mat <- as.matrix(mx_counts[,1:26])
rownames(mat) <- mx_counts$gene

heatmap.2(mat, 
          Colv = NULL,
          dendrogram = "row",
          scale = "row",
          trace = "none",
          col=brewer.pal(11,"RdBu"),
          cexRow = 0.5,
          margins = c(5,5)
          )

##! problem: not all genes are labelled on plot
# need to exprot as pdf with dimensions big enough to show all genes
```

``` {r xcell}



```

